-- Insert sample AircraftManufacturers
INSERT INTO AircraftManufacturers VALUES ('Airbus')
INSERT INTO AircraftManufacturers VALUES ('Beechcraft')
INSERT INTO AircraftManufacturers VALUES ('Boeing')
INSERT INTO AircraftManufacturers VALUES ('Cessna')
INSERT INTO AircraftManufacturers VALUES ('Cirrus')
INSERT INTO AircraftManufacturers VALUES ('Robinson')
INSERT INTO AircraftManufacturers VALUES ('Mikoyan-Gurevich')
INSERT INTO AircraftManufacturers VALUES ('Chotia')
INSERT INTO AircraftManufacturers VALUES ('Antonov')
INSERT INTO AircraftManufacturers VALUES ('Gulfstream')

-- Insert sample AircraftModels
INSERT INTO AircraftModels VALUES ('A340', (SELECT id FROM AircraftManufacturers WHERE name='Airbus'))
INSERT INTO AircraftModels VALUES ('Super King Air 200', (SELECT id FROM AircraftManufacturers WHERE name='Beechcraft'))
INSERT INTO AircraftModels VALUES ('717', (SELECT id FROM AircraftManufacturers WHERE name='Boeing'))
INSERT INTO AircraftModels VALUES ('208 Caravan', (SELECT id FROM AircraftManufacturers WHERE name='Cessna'))
INSERT INTO AircraftModels VALUES ('SR22', (SELECT id FROM AircraftManufacturers WHERE name='Cirrus'))
INSERT INTO AircraftModels VALUES ('R44', (SELECT id FROM AircraftManufacturers WHERE name='Robinson'))
INSERT INTO AircraftModels VALUES ('MiG-23', (SELECT id FROM AircraftManufacturers WHERE name='Mikoyan-Gurevich'))
INSERT INTO AircraftModels VALUES ('Weedhopper', (SELECT id FROM AircraftManufacturers WHERE name='Chotia'))
INSERT INTO AircraftModels VALUES ('An-3', (SELECT id FROM AircraftManufacturers WHERE name='Antonov'))
INSERT INTO AircraftModels VALUES ('GV', (SELECT id FROM AircraftManufacturers WHERE name='Gulfstream'))

-- Insert sample Aircrafts
INSERT INTO Aircrafts (AircraftModelId, SerialNumber, tailnumber) VALUES ((SELECT id FROM AircraftModels WHERE name='A340'), '12-3456', 'N1000')
INSERT INTO Aircrafts (AircraftModelId, SerialNumber, tailnumber) VALUES ((SELECT id FROM AircraftModels WHERE name='Super King Air 200'), '21-3456', 'N1002')
INSERT INTO Aircrafts (AircraftModelId, SerialNumber, tailnumber) VALUES ((SELECT id FROM AircraftModels WHERE name='717'), '001', 'N1002')
INSERT INTO Aircrafts (AircraftModelId, SerialNumber, tailnumber) VALUES ((SELECT id FROM AircraftModels WHERE name='208 Caravan'), '002', 'N1003')
INSERT INTO Aircrafts (AircraftModelId, SerialNumber, tailnumber) VALUES ((SELECT id FROM AircraftModels WHERE name='SR22'), '003', 'N1004')
INSERT INTO Aircrafts (AircraftModelId, SerialNumber, tailnumber) VALUES ((SELECT id FROM AircraftModels WHERE name='R44'), '004', 'N1005')
INSERT INTO Aircrafts (AircraftModelId, SerialNumber, tailnumber) VALUES ((SELECT id FROM AircraftModels WHERE name='MiG-23'), '99999999', 'N1006')
INSERT INTO Aircrafts (AircraftModelId, SerialNumber, tailnumber) VALUES ((SELECT id FROM AircraftModels WHERE name='Weedhopper'), '005', 'N1007')
INSERT INTO Aircrafts (AircraftModelId, SerialNumber, tailnumber) VALUES ((SELECT id FROM AircraftModels WHERE name='An-3'), '99999998', 'N1008')
INSERT INTO Aircrafts (AircraftModelId, SerialNumber, tailnumber) VALUES ((SELECT id FROM AircraftModels WHERE name='GV'), '006', 'N1009')